#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'chef-client'
cookbook 'chef_gem'
cookbook 'rvm', :git => 'https://github.com/fnichol/chef-rvm', :ref => 'v0.9.0'
cookbook 'git'
cookbook 'vim'
cookbook 'user'
cookbook 'fail2ban'
cookbook 'nginx',:git=>'https://github.com/gchef/nginx-cookbook'
cookbook 'redis', :git=>'git://github.com/ctrabold/chef-redis.git'
cookbook 'mysql'
cookbook 'unicorn'
cookbook 'php-fpm',:git=>'git://github.com/yevgenko/cookbook-php-fpm.git'
cookbook 'rails-lastmile',:git=>'git://github.com/cromulus/rails-lastmile.git'
cookbook 'ack'
cookbook 'logrotate'
cookbook 'openssh'
cookbook 'timezone'
